describe('Accessing site', () => {
  it('Pages can be opened', () => {
    cy.visit('/')
    cy.contains('City Bike Rides')
    cy.get('#menu-button').click()
    cy.contains('Bike Stations').click()
    cy.location('pathname', {timeout: 10000}).should('include', '/stations');
    cy.contains('City Bike Stations')
    cy.contains('1').click()
    cy.location('pathname', {timeout: 10000}).should('include', '/stations/1');
    cy.wait(5000)
    cy.contains('Kaivopuisto')
    cy.contains('Brunnsparken')

  })

  it('Single station view shows statistics', () => {
    cy.visit('/stations/1')
    cy.wait(5000)
    cy.contains('Lähdöt: 23802')
    cy.contains('Palautukset: 24288')
    cy.get('#month-select').click()
    cy.contains('Toukokuu').click()
    cy.wait(5000)
    cy.contains('Lähdöt: 5246')
    cy.contains('Palautukset: 5682')
    cy.contains('Toukokuu').click()
    cy.contains('Kesäkuu').click()
    cy.wait(5000)
    cy.contains('Lähdöt: 8860')
    cy.contains('Palautukset: 8828')
    cy.contains('Kesäkuu').click()
    cy.contains('Heinäkuu').click()
    cy.wait(5000)
    cy.contains('Lähdöt: 9696')
    cy.contains('Palautukset: 9778')
  })

  it('Single station view popular station buttons work', () => {
    cy.visit('/stations/1')
    cy.wait(5000)
    cy.contains('Unioninkatu').first().click()
    cy.wait(5000)
    cy.location('pathname', {timeout: 10000}).should('include', '/stations/11')
    cy.contains('Unioninkatu')
    cy.contains('Unionsgatan')
    cy.contains('Liisanpuistikko').first().click()
    cy.wait(5000)
    cy.location('pathname', {timeout: 10000}).should('include', '/stations/16')
    cy.contains('Liisanpuistikko')
    cy.contains('Elisabetsskvären')
  })

  it('Bike Stations can be searched', () => {
    cy.visit('/stations')
    cy.wait(3000)
    cy.get('#search').click().type('herttoniemenranta')
    cy.get('#stationName').contains('Herttoniemenranta')
  })

  it('Bike Rides can be sorted', () => {
    cy.visit('/')
    cy.get('#startDate').click().type('020620211500', {force: true})
    cy.get('#endDate').click().type('030620211500', {force: true})
    cy.wait(10000)
    cy.get('#departureTime').first().should('have.text','2.6.2021 15.00.01')
    cy.get('#lahtoaika').click()
    cy.wait(10000)
    cy.get('#departureTime').first().should('have.text','3.6.2021 15.00.00')
    cy.get('#loppuaika').click()
    cy.wait(10000)
    cy.get('#returnTime').first().should('have.text','2.6.2021 15.01.59')
    cy.get('#lahtoasema').click()
    cy.wait(25000)
    cy.get('#departureStationName').first().should('have.text','Ympyrätalo')
    cy.get('#lahtoasema').click()
    cy.wait(25000)
    cy.get('#departureStationName').first().should('have.text','A.I. Virtasen aukio')
    cy.get('#loppuasema').click()
    cy.wait(25000)
    cy.get('#returnStationName').first().should('have.text','Ympyrätalo')
    cy.get('#loppuasema').click()
    cy.wait(25000)
    cy.get('#returnStationName').first().should('have.text','A.I. Virtasen aukio')
    cy.get('#matka').click()
    cy.wait(15000)
    cy.get('#coveredDistance').first().should('have.text','42.08km')
    cy.get('#matka').click()
    cy.wait(15000)
    cy.get('#coveredDistance').first().should('have.text','0.01km')
    cy.get('#aika').click()
    cy.wait(15000) 
    cy.get('#duration').first().should('have.text','765 tuntia 22min.')
    cy.get('#aika').click()
    cy.wait(15000)
    cy.get('#duration').first().should('have.text','0min.')
  })
})